add maximum units on a truck python3 / java
snowan/interviews pull request #15
Opened 2021-01-09 00:39 UTC by snowan

2021-01-09 00:40 UTC, snowan commented
@sunboman need help review python3?

2021-01-09 05:34 UTC, sunboman requested changes

2021-01-09 05:34 UTC, sunboman commented on 2021/python/maximum-units-on-truck.py
> +    boxTyes.sort(key = lambda x: -x[1])
typo!

2021-01-09 05:34 UTC, sunboman commented on 2021/python/maximum-units-on-truck.py
> +        tuckSize -= b
typo2!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

2021-01-11 01:20 UTC, snowan commented on 2021/python/maximum-units-on-truck.py
> +    boxTyes.sort(key = lambda x: -x[1])
done

2021-01-11 01:20 UTC, snowan commented on 2021/python/maximum-units-on-truck.py
> +        tuckSize -= b
fixed, booooo

2021-01-14 09:06 UTC, merged